[package]
name = "monotonic-blinky"
version = "0.1.0"
edition = "2021"
authors = ["Ivar Jönsson  <ivajns-9@student.ltu.se>"]

[dependencies]
embedded-hal = "1.0.0"
rtt-target = "0.5.0"
panic-halt = "0.2.0"
nrf52840-hal = { path = "../../nrf52840-hal/", features = ["monotonic"] }
cortex-m-rtic = "1.1.4"
fugit = "0.3.7"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }

[[bin]]
name = "rtc"
path = "src/rtc.rs"

[[bin]]
name = "timer"
path = "src/timer.rs"
